### ISSUE TITLE
Weird look of text in Android Pie

### ISSUE THREAD

**Issue by jahirfiquitiva** [andremion/CounterFab#29] opened 2018-12-28 15:55 UTC
Check the screenshot. The text looks outlined for some reason :/
![screenshot_20181228-104950_1](https://user-images.githubusercontent.com/10360816/50520568-175bbd00-0a8f-11e9-9d8f-1b902774b14f.png)

**Comment by andremion** [comment] 2019-01-04 13:57
I'm not able to reproduce it.

![counterfab](https://user-images.githubusercontent.com/12762356/50691414-86ee2100-1028-11e9-9c84-18423c4e71b8.png)

Could you send the details of the device?

**Comment by jahirfiquitiva** [comment] 2019-01-04 15:15
Xiaomi Mi A2
No Custom Roms
Stock Android Pie
🤔

**Comment by andremion** [comment] 2019-01-04 16:09
I've made a change, could you try [this apk](https://www.dropbox.com/s/gr6b3axizq8z9f0/sample-counterfab.apk?dl=0) to see if still happens?

**Comment by jahirfiquitiva** [comment] 2019-01-04 16:47
It looks ok in the apk you sent.

I was thinking and... Could it be possible the issue comes from using AndroidX libraries?

Could you check that and maybe even update your library to use AndroidX too? 🤔

Thanks in advance!

**Comment by andremion** [comment] 2019-02-03 14:47
Hey @jahirfiquitiva 
This bug is not related with AndroidX.
I fixed it and it will be released in `1.2.1`.
Thanks to report it.

**Comment by jahirfiquitiva** [comment] 2019-02-03 14:53
Awesome! Thanks @andremion

**Closed as completed** 2019-02-03 15:11 UTC
Labels: bug
